import { CarModelInsert } from "../carModals";

export const audiModels: CarModelInsert[] = [
  // Models not in an optgroup (series is empty)
  { category: "PKW", brand: "Audi", modelName: "100", series: "" },
  { category: "PKW", brand: "Audi", modelName: "200", series: "" },
  { category: "PKW", brand: "Audi", modelName: "80", series: "" },
  { category: "PKW", brand: "Audi", modelName: "90", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A1", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A2", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A3", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A4", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A4 Allroad", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A5", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A6", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A6 Allroad", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A6 e-tron", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A7", series: "" },
  { category: "PKW", brand: "Audi", modelName: "A8", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Cabriolet", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Coupé", series: "" },
  { category: "PKW", brand: "Audi", modelName: "e-tron", series: "" },
  { category: "PKW", brand: "Audi", modelName: "e-tron GT", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Q2", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Q3", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Q4", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Q4 e-tron", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Q5", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Q6 e-tron", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Q7", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Q8", series: "" },
  { category: "PKW", brand: "Audi", modelName: "Q8 e-tron", series: "" },
  { category: "PKW", brand: "Audi", modelName: "quattro", series: "" },
  { category: "PKW", brand: "Audi", modelName: "R8", series: "" },
  { category: "PKW", brand: "Audi", modelName: "RS2", series: "" },
  { category: "PKW", brand: "Audi", modelName: "RS3", series: "" },
  { category: "PKW", brand: "Audi", modelName: "RS4", series: "" },
  { category: "PKW", brand: "Audi", modelName: "RS5", series: "" },
  { category: "PKW", brand: "Audi", modelName: "RS6", series: "" },
  { category: "PKW", brand: "Audi", modelName: "RS7", series: "" },
  { category: "PKW", brand: "Audi", modelName: "RS e-tron GT", series: "" },
  { category: "PKW", brand: "Audi", modelName: "RSQ3", series: "" },
  { category: "PKW", brand: "Audi", modelName: "RSQ8", series: "" },
  { category: "PKW", brand: "Audi", modelName: "S1", series: "" },
  { category: "PKW", brand: "Audi", modelName: "S2", series: "" },
  { category: "PKW", brand: "Audi", modelName: "S3", series: "" },
  { category: "PKW", brand: "Audi", modelName: "S4", series: "" },
  { category: "PKW", brand: "Audi", modelName: "S5", series: "" },
  { category: "PKW", brand: "Audi", modelName: "S6", series: "" },
  { category: "PKW", brand: "Audi", modelName: "S6 e-tron", series: "" },
  { category: "PKW", brand: "Audi", modelName: "S7", series: "" },
  { category: "PKW", brand: "Audi", modelName: "S8", series: "" },
  { category: "PKW", brand: "Audi", modelName: "SQ2", series: "" },
  { category: "PKW", brand: "Audi", modelName: "SQ5", series: "" },
  { category: "PKW", brand: "Audi", modelName: "SQ6 e-tron", series: "" },
  { category: "PKW", brand: "Audi", modelName: "SQ7", series: "" },
  { category: "PKW", brand: "Audi", modelName: "SQ8", series: "" },
  { category: "PKW", brand: "Audi", modelName: "SQ8 e-tron", series: "" },

  // TT (alle)
  { category: "PKW", brand: "Audi", modelName: "TT (alle) (Alle)", series: "TT (alle)", isLabel: true },
  { category: "PKW", brand: "Audi", modelName: "TT", series: "TT (alle)" },
  { category: "PKW", brand: "Audi", modelName: "TT RS", series: "TT (alle)" },
  { category: "PKW", brand: "Audi", modelName: "TTS", series: "TT (alle)" },

  // Standalone
  { category: "PKW", brand: "Audi", modelName: "V8", series: "" },
 
];