import { CarModelInsert } from "../carModals";

export const bmwModels: CarModelInsert[] = [
  // 1er Reihe
  { category: "PKW", brand: "BMW", modelName: "1er Reihe (Alle)", series: "1er Reihe", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "114", series: "1er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "116", series: "1er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "118", series: "1er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "120", series: "1er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "123", series: "1er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "125", series: "1er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "128", series: "1er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "130", series: "1er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "135", series: "1er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "1er M Coupé", series: "1er Reihe" },

  // 2002 (not in a group)
  { category: "PKW", brand: "BMW", modelName: "2002", series: "" },

  // 2er Reihe
  { category: "PKW", brand: "BMW", modelName: "2er Reihe (Alle)", series: "2er Reihe", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "214 Active Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "214 Gran Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "216", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "216 Active Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "216 Gran Coupé", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "216 Gran Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "218", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "218 Active Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "218 Gran Coupé", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "218 Gran Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "220", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "220 Active Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "220 Gran Coupé", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "220 Gran Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "223 Active Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "225", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "225 Active Tourer", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "228", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "230", series: "2er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "2er Gran Coupé", series: "2er Reihe" },

  // 3er Reihe
  { category: "PKW", brand: "BMW", modelName: "3er Reihe (Alle)", series: "3er Reihe", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "315", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "316", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "318", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "318 Gran Turismo", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "320", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "320 Gran Turismo", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "323", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "324", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "325", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "325 Gran Turismo", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "328", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "328 Gran Turismo", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "330", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "330 Gran Turismo", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "335", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "335 Gran Turismo", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "340", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "340 Gran Turismo", series: "3er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "ActiveHybrid 3", series: "3er Reihe" },

  // 4er Reihe
  { category: "PKW", brand: "BMW", modelName: "4er Reihe (Alle)", series: "4er Reihe", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "418", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "418 Gran Coupé", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "420", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "420 Gran Coupé", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "425", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "425 Gran Coupé", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "428", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "428 Gran Coupé", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "430", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "430 Gran Coupé", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "435", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "435 Gran Coupé", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "440", series: "4er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "440 Gran Coupé", series: "4er Reihe" },

  // 5er Reihe
  { category: "PKW", brand: "BMW", modelName: "5er Reihe (Alle)", series: "5er Reihe", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "518", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "520", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "520 Gran Turismo", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "523", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "524", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "525", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "528", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "530", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "530 Gran Turismo", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "535", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "535 Gran Turismo", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "540", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "545", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "550", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "550 Gran Turismo", series: "5er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "ActiveHybrid 5", series: "5er Reihe" },

  // 6er Reihe
  { category: "PKW", brand: "BMW", modelName: "6er Reihe (Alle)", series: "6er Reihe", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "620 Gran Turismo", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "628", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "630", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "630 Gran Turismo", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "633", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "635", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "640", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "640 Gran Coupé", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "640 Gran Turismo", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "645", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "650", series: "6er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "650 Gran Coupé", series: "6er Reihe" },

  // 7er Reihe
  { category: "PKW", brand: "BMW", modelName: "7er Reihe (Alle)", series: "7er Reihe", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "725", series: "7er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "728", series: "7er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "730", series: "7er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "732", series: "7er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "735", series: "7er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "740", series: "7er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "745", series: "7er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "750", series: "7er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "760", series: "7er Reihe" },
  { category: "PKW", brand: "BMW", modelName: "ActiveHybrid 7", series: "7er Reihe" },

  // 8er Reihe (not in your select, but if needed, add here)

  // Standalone models
  { category: "PKW", brand: "BMW", modelName: "840", series: "" },
  { category: "PKW", brand: "BMW", modelName: "850", series: "" },
  { category: "PKW", brand: "BMW", modelName: "i3", series: "" },
  { category: "PKW", brand: "BMW", modelName: "i4", series: "" },
  { category: "PKW", brand: "BMW", modelName: "i5", series: "" },
  { category: "PKW", brand: "BMW", modelName: "i7", series: "" },
  { category: "PKW", brand: "BMW", modelName: "i8", series: "" },
  { category: "PKW", brand: "BMW", modelName: "iX", series: "" },
  { category: "PKW", brand: "BMW", modelName: "iX1", series: "" },
  { category: "PKW", brand: "BMW", modelName: "iX2", series: "" },
  { category: "PKW", brand: "BMW", modelName: "iX3", series: "" },

  // M-Modelle
  { category: "PKW", brand: "BMW", modelName: "M-Modelle (Alle)", series: "M-Modelle", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "M135", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M140i", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M2", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M235", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M240i", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M3", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M340d", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M340i", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M4", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M440", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M5", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M550", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M6", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M760", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M8", series: "M-Modelle" },
  { category: "PKW", brand: "BMW", modelName: "M850", series: "M-Modelle" },

  // X-Reihe
  { category: "PKW", brand: "BMW", modelName: "X-Reihe (Alle)", series: "X-Reihe", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "ActiveHybrid X6", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X1", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X2", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X3", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X3 M", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X3 M40", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X3 M50", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X4", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X4 M", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X4 M40", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X5", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X5 M", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X5 M50", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X5 M60", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X6", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X6 M", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X6 M50", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X6 M60", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X7", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X7 M50", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "X7 M60", series: "X-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "XM", series: "X-Reihe" },

  // Z-Reihe
  { category: "PKW", brand: "BMW", modelName: "Z-Reihe (Alle)", series: "Z-Reihe", isLabel: true },
  { category: "PKW", brand: "BMW", modelName: "Z1", series: "Z-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "Z3", series: "Z-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "Z3 M", series: "Z-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "Z4", series: "Z-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "Z4 M", series: "Z-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "Z4 M40i", series: "Z-Reihe" },
  { category: "PKW", brand: "BMW", modelName: "Z8", series: "Z-Reihe" },

 
];