import { CarModelInsert } from "../carModals";

export const mercedesBenzModels: CarModelInsert[] = [
    // Models not in an optgroup (series is empty)
    { category: "PKW", brand: "Mercedes_Benz", modelName: "190", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "200", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "220", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "230", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "240", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "250", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "260", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "270", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "280", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "290", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "300", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "320", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "350", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "380", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "400", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "416", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "420", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "450", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "500", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "560", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "600", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "Citan", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "EQA", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "EQB", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "EQC", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "EQE", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "EQE SUV", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "EQS", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "EQS SUV", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "EQT", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "EQV", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "eCitan", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "eSprinter", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "eVito", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "MB 100", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLR", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLS AMG", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "Sprinter", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "T-Klasse", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "Vaneo", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "Vario", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "Viano", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "Vito", series: "" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "Andere", series: "" },
  
    // A-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A-Klasse (Alle)", series: "A-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 140", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 150", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 160", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 170", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 180", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 190", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 200", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 210", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 220", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 250", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 35 AMG", series: "A-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "A 45 AMG", series: "A-Klasse" },
  
    // B-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "B-Klasse (Alle)", series: "B-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "B 150", series: "B-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "B 160", series: "B-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "B 170", series: "B-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "B 180", series: "B-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "B 200", series: "B-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "B 220", series: "B-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "B 250", series: "B-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "B Electric Drive", series: "B-Klasse" },
  
    // CE-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CE-Klasse (Alle)", series: "CE-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CE 200", series: "CE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CE 220", series: "CE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CE 230", series: "CE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CE 280", series: "CE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CE 300", series: "CE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CE 320", series: "CE-Klasse" },
  
    // C-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C-Klasse (Alle)", series: "C-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 160", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 180", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 200", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 220", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 230", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 240", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 250", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 270", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 280", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 300", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 30 AMG", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 320", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 32 AMG", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 350", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 36 AMG", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 400", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 43 AMG", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 450 AMG", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 55 AMG", series: "C-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "C 63 AMG", series: "C-Klasse" },
  
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA-Klasse (Alle)", series: "CLA-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 180", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 180 Shooting Brake", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 200", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 200 Shooting Brake", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 220", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 220 Shooting Brake", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 250", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 250 Shooting Brake", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 35 AMG", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 35 AMG Shooting Brake", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 45 AMG", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA 45 AMG Shooting Brake", series: "CLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLA Shooting Brake", series: "CLA-Klasse" },
  
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLC-Klasse (Alle)", series: "CLC-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLC 160", series: "CLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLC 180", series: "CLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLC 200", series: "CLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLC 220", series: "CLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLC 230", series: "CLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLC 250", series: "CLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLC 350", series: "CLC-Klasse" },
  
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLE-Klasse (Alle)", series: "CLE-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLE 180", series: "CLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLE 200", series: "CLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLE 220", series: "CLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLE 300", series: "CLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLE 450", series: "CLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLE 53 AMG", series: "CLE-Klasse" },
  
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK-Klasse (Alle)", series: "CLK-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 200", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 220", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 230", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 240", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 270", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 280", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 320", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 350", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 430", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 500", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 55 AMG", series: "CLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLK 63 AMG", series: "CLK-Klasse" },
  
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL-Klasse (Alle)", series: "CL-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 160", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 180", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 200", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 220", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 230", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 320", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 420", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 500", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 55 AMG", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 600", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 63 AMG", series: "CL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CL 65 AMG", series: "CL-Klasse" },
  
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS-Klasse (Alle)", series: "CLS-Klasse", isLabel : true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 220", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 220 Shooting Brake", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 250", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 250 Shooting Brake", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 280", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 300", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 320", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 350", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 350 Shooting Brake", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 400", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 400 Shooting Brake", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 450", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 500", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 500 Shooting Brake", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 53 AMG", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 55 AMG", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 63 AMG", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS 63 AMG Shooting Brake", series: "CLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "CLS Shooting Brake", series: "CLS-Klasse" },
  
    // E-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E-Klasse (Alle)", series: "E-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 200", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 220", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 230", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 240", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 250", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 260", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 270", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 280", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 290", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 300", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 320", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 350", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 36 AMG", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 400", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 420", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 430", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 43 AMG", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 450", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 50", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 500", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 53 AMG", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 55 AMG", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 60 AMG", series: "E-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "E 63 AMG", series: "E-Klasse" },
  
    // G-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G-Klasse (Alle)", series: "G-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 230", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 240", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 250", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 270", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 280", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 290", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 300", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 320", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 350", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 400", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 450", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 500", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 55 AMG", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 580", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 63 AMG", series: "G-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "G 65 AMG", series: "G-Klasse" },
  
    // GLA-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLA-Klasse (Alle)", series: "GLA-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLA 180", series: "GLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLA 200", series: "GLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLA 220", series: "GLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLA 250", series: "GLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLA 35 AMG", series: "GLA-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLA 45 AMG", series: "GLA-Klasse" },
  
    // GLB-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLB-Klasse (Alle)", series: "GLB-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLB 180", series: "GLB-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLB 200", series: "GLB-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLB 220", series: "GLB-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLB 250", series: "GLB-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLB 35 AMG", series: "GLB-Klasse" },
  
    // GLC-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC-Klasse (Alle)", series: "GLC-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC 200", series: "GLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC 220", series: "GLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC 250", series: "GLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC 300", series: "GLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC 350", series: "GLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC 400", series: "GLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC 43 AMG", series: "GLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC 450", series: "GLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLC 63 AMG", series: "GLC-Klasse" },
  
    // GLE-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE-Klasse (Alle)", series: "GLE-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 250", series: "GLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 300", series: "GLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 350", series: "GLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 400", series: "GLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 43 AMG", series: "GLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 450", series: "GLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 500", series: "GLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 53 AMG", series: "GLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 580", series: "GLE-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLE 63 AMG", series: "GLE-Klasse" },
  
    // GLK-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLK-Klasse (Alle)", series: "GLK-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLK 200", series: "GLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLK 220", series: "GLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLK 250", series: "GLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLK 280", series: "GLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLK 300", series: "GLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLK 320", series: "GLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLK 350", series: "GLK-Klasse" },
  
    // GL-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GL-Klasse (Alle)", series: "GL-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GL 320", series: "GL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GL 350", series: "GL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GL 400", series: "GL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GL 420", series: "GL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GL 450", series: "GL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GL 500", series: "GL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GL 55 AMG", series: "GL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GL 63 AMG", series: "GL-Klasse" },
  
    // GLS-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLS-Klasse (Alle)", series: "GLS-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLS 350", series: "GLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLS 400", series: "GLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLS 450", series: "GLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLS 500", series: "GLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLS 580", series: "GLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLS 600", series: "GLS-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GLS 63", series: "GLS-Klasse" },
  
    // GT-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "GT-Klasse (Alle)", series: "GT-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "AMG GT", series: "GT-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "AMG GT C", series: "GT-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "AMG GT R", series: "GT-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "AMG GT S", series: "GT-Klasse" },
  
    // ML-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML-Klasse (Alle)", series: "ML-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 230", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 250", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 270", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 280", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 300", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 320", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 350", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 400", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 420", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 430", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 450", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 500", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 55 AMG", series: "ML-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "ML 63 AMG", series: "ML-Klasse" },
  
    // R-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "R-Klasse (Alle)", series: "R-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "R 280", series: "R-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "R 300", series: "R-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "R 320", series: "R-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "R 350", series: "R-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "R 500", series: "R-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "R 63 AMG", series: "R-Klasse" },
  
    // S-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S-Klasse (Alle)", series: "S-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 250", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 260", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 280", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 300", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 320", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 350", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 400", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 420", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 430", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 450", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 500", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 55", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 550", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 560", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 580", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 600", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 63 AMG", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 650", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 65 AMG", series: "S-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "S 680", series: "S-Klasse" },
  
    // SLC-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLC-Klasse (Alle)", series: "SLC-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLC 180", series: "SLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLC 200", series: "SLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLC 250", series: "SLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLC 280", series: "SLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLC 300", series: "SLC-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLC 43 AMG", series: "SLC-Klasse" },
  
    // SLK-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK-Klasse (Alle)", series: "SLK-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK 200", series: "SLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK 230", series: "SLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK 250", series: "SLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK 280", series: "SLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK 300", series: "SLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK 320", series: "SLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK 32 AMG", series: "SLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK 350", series: "SLK-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SLK 55 AMG", series: "SLK-Klasse" },
  
    // SL-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL-Klasse (Alle)", series: "SL-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 230", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 250", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 280", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 300", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 320", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 350", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 380", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 400", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 420", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 43 AMG", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 450", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 500", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 55 AMG", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 560", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 600", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 60 AMG", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 63 AMG", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 65 AMG", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 680", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 70 AMG", series: "SL-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "SL 73 AMG", series: "SL-Klasse" },
  
    // V-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "V-Klasse (Alle)", series: "V-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "V 200", series: "V-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "V 220", series: "V-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "V 230", series: "V-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "V 250", series: "V-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "V 280", series: "V-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "V 300", series: "V-Klasse" },
  
    // X-Klasse
    { category: "PKW", brand: "Mercedes_Benz", modelName: "X-Klasse (Alle)", series: "X-Klasse", isLabel: true },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "X 220", series: "X-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "X 250", series: "X-Klasse" },
    { category: "PKW", brand: "Mercedes_Benz", modelName: "X 350", series: "X-Klasse" }
  ];