import { CarModelInsert } from "../carModals";

export const volkswagenModel: CarModelInsert[] = [
  // Models not in an optgroup (series is empty)
  { category: "PKW", brand: "Volkswagen", modelName: "181", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Amarok", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Arteon", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Beetle", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Bora", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Buggy", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Caddy", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Caddy Maxi", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "CC", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Corrado", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Crafter", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Eos", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "e-up!", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Fox", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "ID.3", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "ID.4", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "ID.5", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "ID.6", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "ID.7", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "ID. Buzz", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Iltis", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Jetta", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Käfer", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Karmann Ghia", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "LT", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Lupo", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "New Beetle", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Phaeton", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Polo", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Routan", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Santana", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Scirocco", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Sharan", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "T1", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "T2", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Taigo", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Taro", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Tayron", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "T-Cross", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Tiguan", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Tiguan Allspace", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Touareg", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Touran", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "T-Roc", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "up!", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Vento", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "XL1", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Andere", series: "" },

  // Golf
  { category: "PKW", brand: "Volkswagen", modelName: "Golf (Alle)", series: "Golf", isLabel: true },
  { category: "PKW", brand: "Volkswagen", modelName: "Golf", series: "Golf" },
  { category: "PKW", brand: "Volkswagen", modelName: "Golf Plus", series: "Golf" },
  { category: "PKW", brand: "Volkswagen", modelName: "Golf Sportsvan", series: "Golf" },

  // Passat (alle)
  { category: "PKW", brand: "Volkswagen", modelName: "Passat (alle) (Alle)", series: "Passat (alle)", isLabel: true },
  { category: "PKW", brand: "Volkswagen", modelName: "Passat", series: "Passat (alle)" },
  { category: "PKW", brand: "Volkswagen", modelName: "Passat Alltrack", series: "Passat (alle)" },
  { category: "PKW", brand: "Volkswagen", modelName: "Passat CC", series: "Passat (alle)" },
  { category: "PKW", brand: "Volkswagen", modelName: "Passat Variant", series: "Passat (alle)" },

  // T3
  { category: "PKW", brand: "Volkswagen", modelName: "T3 (Alle)", series: "T3", isLabel: true },
  { category: "PKW", brand: "Volkswagen", modelName: "T3 andere", series: "T3" },
  { category: "PKW", brand: "Volkswagen", modelName: "T3 Caravelle", series: "T3" },
  { category: "PKW", brand: "Volkswagen", modelName: "T3 Kombi", series: "T3" },
  { category: "PKW", brand: "Volkswagen", modelName: "T3 Multivan", series: "T3" },

  // T4
  { category: "PKW", brand: "Volkswagen", modelName: "T4 (Alle)", series: "T4", isLabel: true },
  { category: "PKW", brand: "Volkswagen", modelName: "T4 andere", series: "T4" },
  { category: "PKW", brand: "Volkswagen", modelName: "T4 California", series: "T4" },
  { category: "PKW", brand: "Volkswagen", modelName: "T4 Caravelle", series: "T4" },
  { category: "PKW", brand: "Volkswagen", modelName: "T4 Kombi", series: "T4" },
  { category: "PKW", brand: "Volkswagen", modelName: "T4 Multivan", series: "T4" },

  // T5
  { category: "PKW", brand: "Volkswagen", modelName: "T5 (Alle)", series: "T5", isLabel: true },
  { category: "PKW", brand: "Volkswagen", modelName: "T5 andere", series: "T5" },
  { category: "PKW", brand: "Volkswagen", modelName: "T5 California", series: "T5" },
  { category: "PKW", brand: "Volkswagen", modelName: "T5 Caravelle", series: "T5" },
  { category: "PKW", brand: "Volkswagen", modelName: "T5 Kombi", series: "T5" },
  { category: "PKW", brand: "Volkswagen", modelName: "T5 Multivan", series: "T5" },
  { category: "PKW", brand: "Volkswagen", modelName: "T5 Shuttle", series: "T5" },
  { category: "PKW", brand: "Volkswagen", modelName: "T5 Transporter", series: "T5" },

  // T6
  { category: "PKW", brand: "Volkswagen", modelName: "T6 (Alle)", series: "T6", isLabel: true },
  { category: "PKW", brand: "Volkswagen", modelName: "T6 andere", series: "T6" },
  { category: "PKW", brand: "Volkswagen", modelName: "T6 California", series: "T6" },
  { category: "PKW", brand: "Volkswagen", modelName: "T6 Caravelle", series: "T6" },
  { category: "PKW", brand: "Volkswagen", modelName: "T6 Kombi", series: "T6" },
  { category: "PKW", brand: "Volkswagen", modelName: "T6 Multivan", series: "T6" },
  { category: "PKW", brand: "Volkswagen", modelName: "T6 Transporter", series: "T6" },

  // T7
  { category: "PKW", brand: "Volkswagen", modelName: "T7 (Alle)", series: "T7", isLabel: true },
  { category: "PKW", brand: "Volkswagen", modelName: "T7 California", series: "T7" },
  { category: "PKW", brand: "Volkswagen", modelName: "T7 Caravelle", series: "T7" },
  { category: "PKW", brand: "Volkswagen", modelName: "T7 Kombi", series: "T7" },
  { category: "PKW", brand: "Volkswagen", modelName: "T7 Multivan", series: "T7" },
  { category: "PKW", brand: "Volkswagen", modelName: "T7 other", series: "T7" },
  { category: "PKW", brand: "Volkswagen", modelName: "T7 Transporter", series: "T7" },
  // Remaining models not in an optgroup
  { category: "PKW", brand: "Volkswagen", modelName: "Taigo", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Taro", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Tayron", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "T-Cross", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Tiguan", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Tiguan Allspace", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Touareg", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Touran", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "T-Roc", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "up!", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "Vento", series: "" },
  { category: "PKW", brand: "Volkswagen", modelName: "XL1", series: "" },
  
];